Repository Team-Omoshiroi/Omoshiroi, pull requests merged in 2023-11, with the labels that each got.

#36 CharacterDataContainer 코드 리팩토링
  Client/Assets/Scripts/Character/CharacterDataContainer.cs
  Client/Assets/Scripts/Character/EquipSystem.cs
Labels: Refactor

#38 EquipSystem 리팩터링, 메소드 추가 #28
  Client/Assets/Scripts/Character/EquipSystem.cs
Labels: Feature, Refactor

#46 ItemSO 스택 관련 멤버변수 추가 #14
  Client/Assets/Scripts/Defines/Interfaces.cs
  Client/Assets/Scripts/Items/BaseConsumable.cs
  Client/Assets/Scripts/Items/BaseItem.cs
  Client/Assets/Scripts/Items/BaseResource.cs
Labels: Refactor

#47 조준/공격 달리기/회피 이벤트에 터치 조작 연결완료
  Client/Assets/InputSystems/ThirdPersonController.cs
  Client/Assets/InputSystems/ThirdPersonController.inputactions
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scripts/Character/FSM.meta
  Client/Assets/Scripts/Character/FSM/BaseState.cs
  Client/Assets/Scripts/Character/FSM/BaseState.cs.meta
  Client/Assets/Scripts/Character/FSM/CharacterStateMachine.cs
  Client/Assets/Scripts/Character/FSM/CharacterStateMachine.cs.meta
  Client/Assets/Scripts/Character/Input/BaseInput.cs
  Client/Assets/Scripts/Character/Input/PlayerInput.cs
  Client/Packages/manifest.json
  Client/Packages/packages-lock.json
  Client/ProjectSettings/ProjectSettings.asset
Labels: Feature, Refactor

#49 Bug: stackble버그수정
  Client/Assets/Scripts/Contoller/InventoryContrller.cs
  Client/Assets/Scripts/Inventory/InventorySO.cs
  Client/Assets/Scripts/Inventory/Test/ItemSO.cs
  Client/Assets/Scripts/Inventory/Test/PickUpSystem.meta
  Client/Assets/Scripts/Inventory/Test/PickUpSystem/Item.cs
  Client/Assets/Scripts/Inventory/Test/PickUpSystem/Item.cs.meta
  Client/Assets/Scripts/Inventory/Test/PickUpSystem/PickUpSystem.cs
  Client/Assets/Scripts/Inventory/Test/PickUpSystem/PickUpSystem.cs.meta
Labels: Fix

#50 CanControl 변수 생성
  Client/Assets/Scripts/Character/Input/PlayerInput.cs
  Client/ProjectSettings/ProjectSettings.asset
Labels: Feature

#52 CharacterStats, BaseWeapon 리팩터링 #14
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Character/EquipSystem.cs
  Client/Assets/Scripts/Items/BaseMagic.cs
  Client/Assets/Scripts/Items/BaseWeapon.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Feature, Refactor

#53 feat: 아이템 줍기
  Client/Assets/Resources/Prefabs/UI/UIInventoryPage.prefab
  Client/Assets/Scenes/InventoryBackup.unity
  Client/Assets/Scripts/Contoller/InventoryContrller.cs
  Client/Assets/Scripts/Inventory/InventorySO.cs
  Client/Assets/Scripts/Inventory/Test/PickUpSystem/Item.cs
  Client/Assets/Scripts/Inventory/Test/PickUpSystem/PickUpSystem.cs
  Client/Assets/Scripts/Inventory/Test/PickUpSystem/TestInventoryPlayerMovement.cs
  Client/Assets/Scripts/Inventory/Test/PickUpSystem/TestInventoryPlayerMovement.cs.meta
  Client/Assets/Scripts/Inventory/Test/PlayerInventory.asset
  Client/Assets/Scripts/Inventory/Test/apple.asset
  Client/Assets/Scripts/Inventory/Test/apple.asset.meta
  Client/Assets/Scripts/Inventory/Test/bag.asset
  Client/Assets/Scripts/Inventory/Test/sowrd.asset
  Client/Assets/Scripts/UI/Inventory/UIInventoryPage.cs
Labels: Feature

#54 CharacterStats 관련 버그 수정 #28
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
Labels: Fix

#57 CharacterBaseStats, CharacterStats 리팩터링 #28
  Client/Assets/Scripts/Character/CharacterBaseStats.cs
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Feature, Refactor

#58 UI:이미지변경
  Client/Assets/Resources/Imges/ArtImg/33.png
  Client/Assets/Resources/Imges/ArtImg/33.png.meta
  Client/Assets/Resources/Imges/ArtImg/44.png
  Client/Assets/Resources/Imges/ArtImg/44.png.meta
Labels: UI

#59 UI:스타트씬 텍스트 배치 수정
  Client/Assets/Scenes/StartScene.unity
Labels: UI

#63 EquipSystem 메소드 추가 #28
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scenes/FarmingBoxTest.unity.meta
  Client/Assets/Scripts/Character/EquipSystem.cs
Labels: Feature

#67 FarmingBox UI, 스크립트 작업 중 #43
  Client/Assets/Resources/Prefabs/UI/UIInventoryPage_FB.prefab
  Client/Assets/Resources/Prefabs/UI/UIInventoryPage_FB.prefab.meta
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scripts/Contoller/InventoryContrller_FB.cs
  Client/Assets/Scripts/Contoller/InventoryContrller_FB.cs.meta
  Client/Assets/Scripts/Inventory/Test/FarmingBoxInventory.asset
  Client/Assets/Scripts/Inventory/Test/FarmingBoxInventory.asset.meta
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
  Client/Assets/Scripts/WorldObject/UIInventoryPage_FB.cs
  Client/Assets/Scripts/WorldObject/UIInventoryPage_FB.cs.meta
  Client/Packages/packages-lock.json
Labels: Feature

#69 Server/web manager
  Client/Assets/Scripts/Managers/ConfigManager.cs
  Client/Assets/Scripts/Managers/WebManager.cs
  Client/Assets/Scripts/Managers/WebManager.cs.meta
Labels: Feature

#71 Client/DataManager
  Client/Assets/Resources/Data.meta
  Client/Assets/Resources/Data/WeaponItem.json
  Client/Assets/Resources/Data/WeaponItem.json.meta
  Client/Assets/Scripts/Data.meta
  Client/Assets/Scripts/Data/Data.Contents.cs
  Client/Assets/Scripts/Data/Data.Contents.cs.meta
  Client/Assets/Scripts/Managers/DataManager.cs
  Client/Assets/Scripts/Managers/DataManager.cs.meta
Labels: Feature

#79 FSM 공격/조준 디버깅 완료
  Client/Assets/Animation/TestAnimator.controller
  Client/Assets/Scripts/Character/FSM/CharacterAimState.cs
  Client/Assets/Scripts/Character/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/FSM/CharacterNoneState.cs
  Client/Assets/Scripts/Character/Input/PlayerInput.cs
  Client/Assets/Scripts/Inventory/Test/TestMagicSO.asset
  Client/Assets/Scripts/Items/AttackData.cs
Labels: Fix

#81 InventorySO 메소드 추가 및 InventoryController_FB, UIInventoryPage_FB 작업 중 #43
  Client/Assets/Resources/Prefabs/UI/UIitem_FB.prefab
  Client/Assets/Resources/Prefabs/UI/UIitem_FB.prefab.meta
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scripts/Contoller/InventoryContrller_FB.cs
  Client/Assets/Scripts/Inventory/InventorySO.cs
  Client/Assets/Scripts/UI/Inventory/MouseFollower.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
  Client/Assets/Scripts/WorldObject/UIInventoryPage_FB.cs
Labels: Feature, Refactor

#83 FSM 공격/낙하 상태 디버깅 완료
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scripts/Character/CharacterAnimationData.cs
  Client/Assets/Scripts/Character/CharacterDataContainer.cs
  Client/Assets/Scripts/Character/FSM/BaseState.cs
  Client/Assets/Scripts/Character/FSM/CharacterAimState.cs
  Client/Assets/Scripts/Character/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/FSM/CharacterFallState.cs
  Client/Assets/Scripts/Character/FSM/CharacterGroudState.cs
  Client/Assets/Scripts/Character/FSM/CharacterNoneState.cs
  Client/Assets/Scripts/Character/FSM/CharacterStateMachine.cs
  Client/Assets/Scripts/Character/Input/PlayerInput.cs
  Client/ProjectSettings/EditorBuildSettings.asset
  Client/ProjectSettings/TagManager.asset
Labels: Fix

#90 Sync Move를 추가
  Client/Assets/Scripts/Character/CharacterDataContainer.cs
  Client/Assets/Scripts/Character/FSM/BaseState.cs
  Client/Assets/Scripts/Character/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/FSM/CharacterGroudState.cs
  Client/Assets/Scripts/Character/FSM/CharacterStateMachine.cs
  Client/Assets/Scripts/Inventory/Test/TestMagicSO.asset
  Client/Assets/Scripts/Items/AttackData.cs
  Client/Assets/Scripts/Items/BaseMagic.cs
Labels: Feature

#94 인벤토리 UI 의 불완전 갱신 해결 #43
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
Labels: Fix, Refactor

#96 feat:인벤토리 패킷 스크립트 추가
  Client/Assets/Resources/Prefabs/PilotPlayer.prefab
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scenes/InventoryBackup.unity
  Client/Assets/Scenes/InventorySystemTestScene.unity
  Client/Assets/Scenes/InventorySystemTestScene.unity.meta
  Client/Assets/Scenes/MergeScene/MergeProtoType.unity
  Client/Assets/Scripts/Contoller/InventoryController.cs
  Client/Assets/Scripts/Contoller/SceneController.cs
  Client/Assets/Scripts/Inventory/PickUpSystem/PickUpSystem.cs
  Client/Assets/Scripts/Web/WebPacket.cs
Labels: Feature

#99 플레이어, 보관함 인벤토리 간의 아이템 이동 구현 완료 #95
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
  Client/Assets/Scripts/Inventory/InventorySO.cs
Labels: Feature, Fix, Refactor

#100 Sync 관련 프리펩 수정 및 사소한 수정
  Client/Assets/Animation/TestClone/CloneController.controller
  Client/Assets/Resources/Prefabs/ClonePlayer.prefab
  Client/Assets/Scripts/Character/Clone/CloneDataContainer.cs
  Client/Assets/Scripts/Character/Input/EnemyInput.cs
  Client/Assets/Scripts/Character/Input/PlayerInput.cs
  Client/Assets/Scripts/Character/Pilot/FSM/BaseState.cs
Labels: Fix

#106 FarmingBox Prefab 추가 #43
  Client/Assets/Resources/Prefabs/FarmingBox.prefab
  Client/Assets/Resources/Prefabs/FarmingBox.prefab.meta
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Feature

#108 Clone 위치 Sync 적용
  Client/Assets/Resources/Prefabs/PilotPlayer.prefab
  Client/Assets/Scripts/Character/Clone/CloneMovement.cs
Labels: Feature

#115 조준 및 이동 방향에 따라 뒤집거나 돌리는 기능 완성
  Client/Assets/Animation/TestPilot/TestAim.anim
  Client/Assets/Animation/TestPilot/TestComboAttack 1.anim
  Client/Assets/Animation/TestPilot/TestComboAttack 2.anim
  Client/Assets/Animation/TestPilot/TestDodge.anim
  Client/Assets/Animation/TestPilot/TestFall.anim
  Client/Assets/Animation/TestPilot/TestIdle.anim
  Client/Assets/Animation/TestPilot/TestRun.anim
  Client/Assets/Animation/TestPilot/TestWalk.anim
  Client/Assets/Resources/Prefabs/PilotPlayer.prefab
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Samples/Adaptive Performance/5.0.0/Environment/blue.mat
  Client/Assets/Samples/Adaptive Performance/5.0.0/Environment/red.mat
  Client/Assets/Scripts/Character/CharacterSpriteRotator.cs
  Client/Assets/Scripts/Character/CharacterSpriteRotator.cs.meta
  Client/Assets/Scripts/Character/Clone/AnimationControllerFSM/CloneStateMachine.cs
  Client/Assets/Scripts/Character/Clone/CloneDataContainer.cs
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
  Client/Assets/Scripts/Character/Pilot/FSM/BaseState.cs
Labels: Feature

#116 바닥을 뚥고 들어가는 버그 수정.
  Client/Assets/Animation/TestPilot/TestComboAttack 1.anim
  Client/Assets/Animation/TestPilot/TestComboAttack 2.anim
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scripts/Character/CharacterSpriteRotator.cs
Labels: Fix

#117 Sync Motion 연결 완료
  Client/Assets/Scripts/Character/CharacterSpriteRotator.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAimState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAirState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterFallState.cs
Labels: Feature

#119 공격 제작 시작
  Client/Assets/Scripts/Character/Attack.meta
  Client/Assets/Scripts/Character/Attack/BaseAttack.cs
  Client/Assets/Scripts/Character/Attack/BaseAttack.cs.meta
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs.meta
Labels: Feature

#120 HealthSystem 개선 및 서버 통신 부분 틀 구현 #118
  Client/Assets/Scripts/Character/HealthSystem.cs
Labels: Feature, Refactor

#123 BaseAttack 업데이트
  Client/Assets/Scripts/Character/Attack/BaseAttack.cs
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs
Labels: Feature

#124 Attack 구조에 대한 설명 추가
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
Labels: Docs

#126 Protobuf 패킷 정의 수정
  Common/Packet/bin/Protocol.proto
Labels: Feature

#127 Attack Manager 수정 및 설명 추가
  Client/Assets/Scripts/Character/Attack/BaseAttack.cs
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Defines/Enums.cs
  Client/Assets/Scripts/Managers/AttackManager.cs
  Client/Assets/Scripts/Managers/RangeAttackManager.cs
  Client/Assets/Scripts/Managers/RangeAttackManager.cs.meta
Labels: Feature, Refactor

#130 공격 진행 및 프리펩 수정
  Client/Assets/Resources/Mesh.meta
  Client/Assets/Resources/Mesh/MeleeAttackArea1.fbx
  Client/Assets/Resources/Mesh/MeleeAttackArea1.fbx.meta
  Client/Assets/Resources/Mesh/MeleeAttackArea2.fbx
  Client/Assets/Resources/Mesh/MeleeAttackArea2.fbx.meta
  Client/Assets/Resources/Mesh/SquareUV.png
  Client/Assets/Resources/Mesh/SquareUV.png.meta
  Client/Assets/Resources/Mesh/WeaponQuad.fbx
  Client/Assets/Resources/Mesh/WeaponQuad.fbx.meta
  Client/Assets/Resources/Prefabs/ClonePlayer.prefab
  Client/Assets/Resources/Prefabs/PilotPlayer.prefab
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs
Labels: Feature, Fix

#133 CharacterDataContainer, CloneDataContainer 리팩터링
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scripts/Character/Clone/CloneDataContainer.cs
  Client/Assets/Scripts/Character/DataContainer.cs
  Client/Assets/Scripts/Character/DataContainer.cs.meta
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
  Client/Assets/Scripts/Inventory/Model/FarmingBoxInventory_Test.asset
  Client/Assets/Scripts/Inventory/Model/FarmingBoxInventory_Test.asset.meta
Labels: Refactor

#134 feat:원거리공격
  Client/Assets/ProPixelizer/ExampleAssets/Alpha/AlphaExample.mat
  Client/Assets/Resources/Prefabs/ObjRange.prefab
  Client/Assets/Resources/Prefabs/ObjRange.prefab.meta
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scenes/RangeAttackTestScene.unity
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/ProjectSettings/TagManager.asset
Labels: Feature

#135 공격 관련 스크립트 수정.
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scripts/Character/Attack/BaseAttack.cs
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Character/DataContainer.cs
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
  Client/ProjectSettings/ProjectSettings.asset
Labels: Feature, Refactor

#136 HealthSystem 서버 연동 구현 #118
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
Labels: Feature, Refactor

#137 Server/HealthSystem
  Server/Server/Game/Object/GameObject.cs
  Server/Server/Game/Object/Player.cs
  Server/Server/Game/Room/GameRoom.cs
  Server/Server/Packet/PacketHandler.cs
Labels: Feature

#139 버그 수정.
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs
Labels: Fix

#140 변수바꿈
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
Labels: Fix

#141 체력 변동, HealthSystem 과 서버 연동 부분 리팩터링 #118
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
Labels: Refactor

#142 간편한 테스트를 위한 FarmingBox 리팩터링 #128
  Client/Assets/Resources/Prefabs/FarmingBox.prefab
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Refactor

#143 공격 수정 중
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs
  Client/Assets/Scripts/Character/Input/BaseInput.cs
  Client/Assets/Scripts/Character/Pilot/FSM/BaseState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAimState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterNoneState.cs
  Client/Assets/Scripts/Items/AttackData.cs
  Client/Assets/Scripts/Managers/AttackManager.cs
Labels: Feature, Fix

#144 CharacterStats 버그픽스, 리팩터링 #28
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Fix, Refactor

#147 CharacterStats HP 프로퍼티 수정 #118
  Client/Assets/Scripts/Character/CharacterStats.cs
Labels: Fix

#148 CharacterStats 수정 2차
  Client/Assets/Scripts/Character/CharacterStats.cs
Labels: Fix

#149 Sync 적용
  Client/Assets/Scripts/Character/Clone/AnimationControllerFSM/CloneStateMachine.cs
  Client/Assets/Scripts/Character/Pilot/CharacterMovement.cs
  Client/Assets/Scripts/Character/Pilot/FSM/BaseState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAimState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAirState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterFallState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterGroudState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterNoneState.cs
  Client/Assets/Scripts/Character/Sync/CloneSync.cs
  Client/Assets/Scripts/Character/Sync/PilotSync.cs
  Client/Assets/Scripts/Character/Sync/SyncModule.cs
  Client/Assets/Scripts/Managers/NetworkManager.cs
  Client/Assets/Scripts/Managers/ObjectManager.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Client/Assets/Scripts/Packet/Protocol.cs
  Common/Packet/bin/Protocol.cs
  Common/Packet/bin/Protocol.proto
Labels: Feature, Refactor

#150 CharcterStats 3차 수정...
  Client/Assets/Scripts/Character/CharacterStats.cs
Labels: Fix

#151 4
  Client/Assets/Scripts/Character/CharacterStats.cs
Labels: Fix

#153 HealthSystem 개선 #118
  Client/Assets/Scripts/Character/HealthSystem.cs
Labels: Refactor

#154 DataContainer, HealthSystem 리팩터링 #118
  Client/Assets/Scripts/Character/DataContainer.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
Labels: Fix, Refactor

#156 Sync 변경 관련 버그 수정 진행 중
  Client/Assets/Resources/Material/Default.mat
  Client/Assets/Scripts/Character/CharacterSpriteRotator.cs
  Client/Assets/Scripts/Character/Clone/AnimationControllerFSM/CloneStateMachine.cs
  Client/Assets/Scripts/Character/Clone/CloneMovement.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAirState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterFallState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterGroudState.cs
  Client/Assets/Scripts/Character/Sync/CloneSync.cs
  Client/Assets/Scripts/Character/Sync/PilotSync.cs
  Client/Assets/Scripts/Character/Sync/SyncModule.cs
  Client/Assets/Scripts/Managers/NetworkManager.cs
  Client/Assets/Scripts/Managers/ObjectManager.cs
  Client/Assets/Scripts/Packet/ClientPacketManager.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Client/Assets/Scripts/Packet/Protocol.cs
  Common/Packet/bin/ClientPacketManager.cs
  Common/Packet/bin/Protocol.cs
  Common/Packet/bin/Protocol.proto
  Common/Packet/bin/ServerPacketManager.cs
  Server/Server/Game/Object/GameObject.cs
  Server/Server/Game/Room/GameRoom.cs
  Server/Server/Game/Room/Map.cs
  Server/Server/Packet/PacketHandler.cs
  Server/Server/Packet/Protocol.cs
  Server/Server/Packet/ServerPacketManager.cs
Labels: Fix, Refactor

#157 Sync motion 수정 완료
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scripts/Character/CharacterSpriteRotator.cs
  Client/Assets/Scripts/Character/Clone/AnimationControllerFSM/CloneStateMachine.cs
  Client/Assets/Scripts/Character/Clone/CloneMovement.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAimState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterFallState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterNoneState.cs
  Client/ProjectSettings/TimelineSettings.asset
Labels: Fix

#161 파밍박스 로직 초기코드 추가
  Server/Server/Game/Object/FarmingBox.cs
  Server/Server/Game/Object/GameObject.cs
  Server/Server/Game/Room/GameRoom.cs
  Server/Server/Packet/PacketHandler.cs
  Server/Server/Packet/Protocol.cs
  Server/Server/Packet/ServerPacketManager.cs
Labels: Feature

#162 Sync 디버깅
  Client/Assets/Resources/Prefabs/ClonePlayer.prefab
  Client/Assets/Resources/Prefabs/PilotPlayer.prefab
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Scenes/MergeScene/MergeProtoType.unity
  Client/Assets/Scripts/Character/Clone/CloneMovement.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAimState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterGroudState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterIdleState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterRunState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterWalkState.cs
  Client/Assets/Scripts/Character/Sync/CloneSync.cs
  Client/Assets/Scripts/Character/Sync/PilotSync.cs
Labels: Fix

#163 FarmingBox 인벤토리 json 파일 추가 #128
  Client/Assets/Resources/Data/FarmingBoxInventory.json
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
  Client/Assets/Scripts/Data/Data.Contents.cs
  Client/Assets/Scripts/Managers/DataManager.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Feature, Refactor

#164 Bug: ui hp 값이 안받아와짐
  Client/Assets/Resources/Prefabs/ObjRange.prefab
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/UI/UIController.cs
Labels: Bug

#165 오타 수정
  Client/Assets/Scripts/Data/Data.Contents.cs
Labels: Fix

#166 Range attack2 song
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
  Client/Assets/Scripts/UI/UIController.cs
  Client/ProjectSettings/TagManager.asset
Labels: Fix

#168 공격 방향 등 공격에 관련된 디버깅
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Managers/AttackManager.cs
Labels: Fix

#170 클라이언트-서버 farmingBox 연동 작업 중 #128
  Client/Assets/Resources/Prefabs/FarmingBox.prefab
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
  Client/Assets/Scripts/Data/Data.Contents.cs
  Client/Assets/Scripts/Managers/DataManager.cs
  Client/Assets/Scripts/Packet/ClientPacketManager.cs
  Client/Assets/Scripts/Packet/Protocol.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
  Common/Packet/bin/Protocol.cs
Labels: Feature, Refactor

#171 DataManager, json 수정 #128
  Data.Contents.cs
  DataManager.cs
  FarmingBox.cs
  FarmingBoxInventory.json
  WeaponItem.json
Labels: Feature, Refactor

#172 입력에 대한 전처리 지시어 추가
  Client/Assets/Scripts/Character/Input/PlayerInput.cs
Labels: Fix

#173 DataManager, json 2차 수정 #128
  Client/Assets/Resources/Data/WeaponItem.json
  Client/Assets/Scripts/Data/Data.Contents.cs
  Client/Assets/Scripts/Managers/DataManager.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
  Data.Contents.cs
  DataManager.cs
  FarmingBox.cs
  FarmingBoxInventory.json
  WeaponItem.json
Labels: Feature, Refactor

#174 Sync 공격 수정
  Client/Assets/Adaptive Performance/AdaptivePerformanceGeneralSettings.asset
  Client/Assets/Resources/Prefabs/ClonePlayer.prefab
  Client/Assets/Resources/Prefabs/Map.meta
  Client/Assets/Resources/Prefabs/Map/Voxel.prefab
  Client/Assets/Resources/Prefabs/Map/Voxel.prefab.meta
  Client/Assets/Resources/Prefabs/PilotPlayer.prefab
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/LoadingScene.unity
  Client/Assets/Scenes/MergeScene/MergeProtoType.unity
  Client/Assets/Scenes/RobbyScene.unity
  Client/Assets/Scenes/StartScene.unity
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Character/Clone/CloneDataContainer.cs
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
  Client/Assets/Scripts/Character/Sync/PilotSync.cs
  Client/Assets/Scripts/Character/Sync/SyncModule.cs
  Client/Assets/Scripts/Contoller/SceneController.cs
  Client/Assets/Scripts/Managers/NetworkManager.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Client/Assets/Scripts/UI/LobbyUIController.cs
  Client/ProjectSettings/EditorBuildSettings.asset
  Server/Server/Game/Object/FarmingBox.cs
  Server/Server/Game/Object/GameObject.cs
  Server/Server/Game/Object/Player.cs
  Server/Server/Game/Room/GameRoom.cs
  Server/Server/Packet/PacketHandler.cs
  Server/Server/Packet/Protocol.cs
  Server/Server/Program.cs
  Server/Server/Session/ClientSession.cs
Labels: Fix

#175 FarmingBox 서버 통신 구현 #128
  Client/Assets/Resources/Prefabs/FBSpawner.prefab
  Client/Assets/Resources/Prefabs/FBSpawner.prefab.meta
  Client/Assets/Resources/Prefabs/FarmingBox.prefab
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
  Client/Assets/Scripts/WorldObject/FarmingBoxSpawner.cs
  Client/Assets/Scripts/WorldObject/FarmingBoxSpawner.cs.meta
Labels: Feature, Refactor

#177 FarmingBoxTest Scene 추가. FarmingBox가 안 열리는 오류 수정 중 #128
  Client/Assets/Scenes/FarmingTest.unity
  Client/Assets/Scenes/FarmingTest.unity.meta
  Client/Assets/Scripts/Character/DataContainer.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Character/Sync/PilotSync.cs
  Client/Assets/Scripts/Character/Sync/SyncModule.cs
  Client/Assets/Scripts/Packet/ClientPacketManager.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Client/Assets/Scripts/Packet/Protocol.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
  Common/Packet/bin/ClientPacketManager.cs
  Common/Packet/bin/Protocol.cs
  Common/Packet/bin/Protocol.proto
  Server/Server/Packet/PacketHandler.cs
Labels: Bug

#178 씬바꾸기
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/RobbyScene.unity
Labels: Feature

#182 Server/리팩터링 & Array.Copy => Buffer.BlockCopy 변경
  Common/Packet/bin/GenProtoDummyClient.bat
  Server/DummyClient/Packet/PacketHandler.cs
  Server/DummyClient/Packet/Protocol.cs
  Server/DummyClient/Program.cs
  Server/Server/Data.Contents/Data.Contents.cs
  Server/Server/Game/Object/FarmingBox.cs
  Server/Server/Game/Object/Player.cs
  Server/Server/Game/Room/GameRoom.cs
  Server/Server/Packet/PacketHandler/FarmingBoxHandler.cs
  Server/Server/Packet/PacketHandler/PlayerHandler.cs
  Server/Server/Packet/Protocol.cs
  Server/Server/Packet/ServerPacketManager.cs
  Server/Server/Program.cs
  Server/Server/Session/ClientSession.cs
  Server/ServerCore/RecvBuffer.cs
Labels: Refactor

#183 Sync 시점 변경
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterFallState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterWalkState.cs
Labels: Fix

#184 천천히 멈추는 경우에 움직임 패킷 보내기
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterIdleState.cs
Labels: Fix

#186 FarmingBox 가 열리지 않는 버그 수정 #128
  Client/Assets/Resources/Prefabs/FBSpawner.prefab
  Client/Assets/Resources/Prefabs/FBSpawner.prefab.meta
  Client/Assets/Resources/Prefabs/FieldObjectSpawner.prefab
  Client/Assets/Resources/Prefabs/FieldObjectSpawner.prefab.meta
  Client/Assets/Resources/Prefabs/PilotPlayer.prefab
  Client/Assets/Scenes/FarmingBoxTest.unity
  Client/Assets/Scenes/FarmingTest.unity
  Client/Assets/Scripts/WorldObject/BattleFieldObjectSpawner.cs
  Client/Assets/Scripts/WorldObject/BattleFieldObjectSpawner.cs.meta
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Fix, Refactor

#190 FarmingBox 패킷 생성 및 처리 부분 작업 중 #128
  Client/Assets/Scenes/FarmingTest.unity
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
  Client/Assets/Scripts/Data/Data.Contents.cs
  Client/Assets/Scripts/Managers/DataManager.cs
  Client/Assets/Scripts/WorldObject/BattleFieldObject.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Feature, Refactor

#191 Sync 디버깅
  Client/Assets/Scripts/Character/Clone/AnimationControllerFSM/CloneStateMachine.cs
  Client/Assets/Scripts/Character/Pilot/FSM/BaseState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAimState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterFallState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterIdleState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterNoneState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterRunState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterStateMachine.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterWalkState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CombineStateMachine.cs
  Client/ProjectSettings/TimeManager.asset
Labels: Fix

#195 가만히 서 있는 경우에 회피하는 방향 수정
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
Labels: Fix

#198 FarmingBox 패킷 통신 구현 완료 #128
  Client/Assets/Scripts/Data/Data.Contents.cs
  Client/Assets/Scripts/Items/BaseMagic.cs
  Client/Assets/Scripts/Managers/DataManager.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Feature, Refactor

#199 Server/핑퐁 체크 시스템(유령 세션 종료)
  Client/Assets/Scripts/Packet/ClientPacketManager.cs
  Client/Assets/Scripts/Packet/PacketHandler.cs
  Client/Assets/Scripts/Packet/Protocol.cs
  Common/Packet/bin/ClientPacketManager.cs
  Common/Packet/bin/Protocol.cs
  Common/Packet/bin/Protocol.proto
  Common/Packet/bin/ServerPacketManager.cs
  Server/Server/Game/Job/JobSerializer.cs
  Server/Server/Game/Room/GameLogic.cs
  Server/Server/Game/Room/RoomManager.cs
  Server/Server/Packet/PacketHandler/PlayerHandler.cs
  Server/Server/Packet/Protocol.cs
  Server/Server/Packet/ServerPacketManager.cs
  Server/Server/Program.cs
  Server/Server/RoomManager.cs
  Server/Server/Session/ClientSession.cs
  Server/Server/Session/SessionManager.cs
Labels: Feature

#205 패킷 수정
  Common/Packet/bin/Protocol.proto
  Server/AccountServer/Program.cs
  Server/DummyClient/Packet/ClientPacketManager.cs
  Server/DummyClient/Packet/PacketHandler.cs
  Server/DummyClient/Packet/PacketQueue.cs
  Server/DummyClient/Packet/Protocol.cs
  Server/DummyClient/ServerSession.cs
  Server/Server/Game/Room/GameRoom.cs
  Server/Server/Packet/PacketHandler/FarmingBoxHandler.cs
  Server/Server/Session/ClientSession.cs
Labels: Feature

#207 Sync module에 맞추어 수정
  Client/Assets/Scripts/Character/Clone/AnimationControllerFSM/CloneStateMachine.cs
  Client/Assets/Scripts/Character/Clone/CloneMovement.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
Labels: Fix, Refactor

#208 Clone Sync 수정
  Client/Assets/Scripts/Character/Clone/AnimationControllerFSM/CloneStateMachine.cs
  Client/Assets/Scripts/Character/Clone/CloneMovement.cs
Labels: Fix, Refactor

#209 AccountServer/Swagger 세팅 완료
  Server/AccountServer/Controllers/AccountController.cs
  Server/AccountServer/Program.cs
Labels: Feature

#212 Lobby scene 버그 수정
  Client/Assets/Resources/Prefabs/UI/UILobby.prefab
  Client/Assets/Resources/Prefabs/UI/UIOption.prefab
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scripts/UI/Inventory/UIManager.cs
Labels: Fix

#215 DB 재설계에 따른 변수명 재정의
  Client/Assets/Scripts/Character/Attack/BaseAttack.cs
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs
  Client/Assets/Scripts/Character/Attack/PlayerAttackController.cs
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Character/Clone/CloneDataContainer.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterStateMachine.cs
  Client/Assets/Scripts/Character/Sync/SyncModule.cs
  Client/Assets/Scripts/Items/BaseWeapon.cs
Labels: Refactor

#216 닷지 중에 공격이 불가능 하도록 수정
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterNoneState.cs
Labels: Fix

#217 StorageScene 로비로 돌아가는 기능 구현
  Client/Assets/Scenes/FarmingTest.unity
  Client/Assets/Scenes/StorageScene.unity
  Client/Assets/Scenes/StorageScene.unity.meta
  Client/Assets/Scripts/UI/StorageSceneController.cs
  Client/Assets/Scripts/UI/StorageSceneController.cs.meta
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Feature, UI

#224 길 찾기 AI 오작동 수정 #214
  Client/Assets/Scenes/AITestScene/AITestScene.unity
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
Labels: Fix, Refactor

#225 Refactor:UICotroller 기능개선
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scripts/UI/LobbyUIController.cs
Labels: Refactor

#227 UI: Lobby씬 완성
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scripts/UI/LobbyUIController.cs
Labels: UI

#230 NPC AI 행동 상태 임시 구현 및 정리 #214
  Client/Assets/Animation/Monster/Skeleton.meta
  Client/Assets/Animation/Monster/Skeleton/SkeletonOverrideController.overrideController
  Client/Assets/Animation/Monster/Skeleton/SkeletonOverrideController.overrideController.meta
  Client/Assets/Animation/Monster/SkeletonOverrideController.overrideController
  Client/Assets/Animation/Monster/SkeletonOverrideController.overrideController.meta
  Client/Assets/Attack_NPC_Skeleton.anim
  Client/Assets/Attack_NPC_Skeleton.anim.meta
  Client/Assets/Externals/DNFBitBitv2/DNFBitBitv2 SDF.asset.meta
  Client/Assets/Externals/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Attack.png.meta
  Client/Assets/Externals/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Dead.png.meta
  Client/Assets/Externals/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Hit.png.meta
  Client/Assets/Externals/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Idle.png.meta
  Client/Assets/Externals/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton React.png.meta
  Client/Assets/Externals/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Walk.png.meta
  Client/Assets/Rendering/Billboard.shadergraph
  Client/Assets/Rendering/TestShader.shader
  Client/Assets/Rendering/TestShader.shader.meta
  Client/Assets/Resources/Prefabs/TestNPC.prefab
  Client/Assets/Scenes/AITestScene/AITestScene.unity
  Client/Assets/Scripts/Character/Clone/AnimationControllerFSM/CloneStateMachine.cs
  Client/Assets/Scripts/Character/Defines/Enums.cs
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
  Client/Assets/Scripts/Character/Pilot/FSM/BaseState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterAimState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterFallState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterGroudState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterIdleState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterNoneState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterRunState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterStateMachine.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterWalkState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CombineStateMachine.cs
  Client/Assets/Skeleton Attack_0.controller
  Client/Assets/Skeleton Attack_0.controller.meta
Labels: Feature, Refactor

#236 UI 체력 표시 플래이어만 표시되도록 수정 및 죽는 이벤트 추가.
  Client/Assets/Resources/Prefabs/UI/_UI.prefab
  Client/Assets/Resources/Prefabs/UI/_UI.prefab.meta
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
Labels: Feature, Fix

#237 AI 행동 양식에 대한 기본 상태 구현 완료 #214
  Client/Assets/Animation/TestPilot/TestAnimator.controller
  Client/Assets/Scenes/AITestScene/AITestScene.unity
  Client/Assets/Scripts/Character/Defines/Enums.cs
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
Labels: Feature, Refactor

#238 공격 속도 및 회피 무적 적용
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scripts/Character/Attack/BaseAttack.cs
  Client/Assets/Scripts/Character/Attack/MeleeAttack.cs
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Inventory/Test/TestBaseStatsSO.asset
  Client/Assets/Scripts/Managers/AttackManager.cs
Labels: Feature, Fix

#240 AI 사망 시 상태를 갱신하지 않도록 수정 #214
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
Labels: Fix, Refactor

#241 테스트용 AI 구현 완료 #214
  Client/Assets/Resources/Prefabs/AITest.prefab
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
Labels: Feature, Fix, Refactor

#242 Test npc 완성
  Client/Assets/Resources/Prefabs/AITest.prefab
  Client/Assets/Resources/Prefabs/Manager.meta
  Client/Assets/Resources/Prefabs/Manager/AttackManager.prefab
  Client/Assets/Resources/Prefabs/Manager/AttackManager.prefab.meta
  Client/Assets/Resources/Prefabs/TestNPC.prefab
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scenes/PlayerTestScene/NavMesh.asset
  Client/Assets/Scenes/PlayerTestScene/NavMesh.asset.meta
  Client/Assets/Scripts/Character/CharacterSpriteRotator.cs
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
Labels: Feature, Fix

#245 AI 공격 상태 개선
  Client/Assets/Animation/Monster/Skeleton/SkeletonOverrideController.overrideController
  Client/Assets/Resources/Prefabs/AITest.prefab
  Client/Assets/Resources/Prefabs/DeadNPCBody.prefab
  Client/Assets/Resources/Prefabs/DeadNPCBody.prefab.meta
  Client/Assets/Scenes/AITestScene/AITestScene.unity
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
Labels: Feature, Fix

#246 Sync packet
  Client/Assets/Externals/ClassicPixelRPGUI/Fonts/PixelSplitter-Bold SDF.asset
  Client/Assets/GSpreadSheets.meta
  Client/Assets/GSpreadSheets/Editor.meta
  Client/Assets/GSpreadSheets/Editor/GSpreadSheetsToJson.cs
  Client/Assets/GSpreadSheets/Editor/GSpreadSheetsToJson.cs.meta
  Client/Assets/GSpreadSheets/Editor/Google.Apis.Auth.dll
  Client/Assets/GSpreadSheets/Editor/Google.Apis.Auth.dll.meta
  Client/Assets/GSpreadSheets/Editor/Google.Apis.Core.dll
  Client/Assets/GSpreadSheets/Editor/Google.Apis.Core.dll.meta
  Client/Assets/GSpreadSheets/Editor/Google.Apis.PlatformServices.dll
  Client/Assets/GSpreadSheets/Editor/Google.Apis.PlatformServices.dll.meta
  Client/Assets/GSpreadSheets/Editor/Google.Apis.Sheets.v4.dll
  Client/Assets/GSpreadSheets/Editor/Google.Apis.Sheets.v4.dll.meta
  Client/Assets/GSpreadSheets/Editor/Google.Apis.dll
  Client/Assets/GSpreadSheets/Editor/Google.Apis.dll.meta
  Client/Assets/GSpreadSheets/Editor/LICENSE-2.0.txt
  Client/Assets/GSpreadSheets/Editor/LICENSE-2.0.txt.meta
  Client/Assets/GSpreadSheets/Editor/Newtonsoft.Json.dll
  Client/Assets/GSpreadSheets/Editor/Newtonsoft.Json.dll.meta
  Client/Assets/GSpreadSheets/GSheetJson v2 Tutorial.pdf
  Client/Assets/GSpreadSheets/GSheetJson v2 Tutorial.pdf.meta
  Client/Assets/GSpreadSheets/SpreadSheetTemplate.xlsx
  Client/Assets/GSpreadSheets/SpreadSheetTemplate.xlsx.meta
  Client/Assets/Resources/Data/LoginStatus.json
  Client/Assets/Resources/Data/LoginStatus.json.meta
  Client/Assets/Resources/Data/Stat.json
  Client/Assets/Resources/Data/Stat.json.meta
  Client/Assets/Resources/Data/Weapon.json
  Client/Assets/Resources/Data/Weapon.json.meta
  Client/Assets/Resources/Fonts/PFStardusts SDF.asset
  Client/Assets/Resources/Fonts/PFStardusts SDF.asset.meta
  Client/Assets/Scenes/LoginScene.unity
  Client/Assets/Scenes/LoginScene.unity.meta
  Client/Assets/Scenes/StartScene.unity
  Client/Assets/Scripts/Character/Sync/SyncModule.cs
  Client/Assets/Scripts/Contoller/InventoryController.cs
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
  Client/Assets/Scripts/Contoller/LoginSceneController.cs
  Client/Assets/Scripts/Contoller/LoginSceneController.cs.meta
  Client/Assets/Scripts/Contoller/SceneController.cs
  Client/Assets/Scripts/Data/Data.Contents.cs
  Client/Assets/Scripts/Inventory/InventorySO.cs
  Client/Assets/Scripts/Items/BaseItem.cs
  Client/Assets/Scripts/Managers/DataManager.cs
  Client/Assets/Scripts/Managers/LoginManager.cs
  Client/Assets/Scripts/Managers/LoginManager.cs.meta
  Client/Assets/Scripts/Managers/WebManager.cs
  Client/Assets/Scripts/Packet/ClientPacketManager.cs
  Client/Assets/Scripts/Web/WebPacket.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
  Client/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Client/ProjectSettings/EditorBuildSettings.asset
Labels: Feature, Fix

#252 싱글 NPC 전투 배치
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/birchTree.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/birchTree_leafless.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/oakTree.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/oakTree_leafless.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/pineTree.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/pineTree02.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/pineTree03.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/pineTree04.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/pineTree05.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/rock01.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/rock02.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/rock03.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/rockGroup01.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/rockGroup02.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/rockGroup03.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/tree.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/treeStump.prefab
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Prefabs/tree_leafless.prefab
  Client/Assets/PolygonFantasyKingdom.meta
  Client/Assets/Resources/Prefabs/AITest.prefab
  Client/Assets/Resources/Prefabs/UI/_UI.prefab
  Client/Assets/Samples/Adaptive Performance/5.0.0/Environment/red.mat
  Client/Assets/Scenes/BattleGroundScene.meta
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/BattleGroundScene/NavMesh.asset
  Client/Assets/Scenes/BattleGroundScene/NavMesh.asset.meta
  Client/Assets/greyRoadStudio.meta
Labels: Feature

#253 NPC 경로 추가
  Client/Assets/Scenes/BattleGroundScene.unity
Labels: Fix

#254 카메라와 Input을 플래이어와 분리
  Client/Assets/Resources/Prefabs/Camera.prefab
  Client/Assets/Resources/Prefabs/Camera.prefab.meta
  Client/Assets/Resources/Prefabs/PilotPlayer.prefab
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scripts/CameraMovement.cs
  Client/Assets/Scripts/CameraMovement.cs.meta
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
Labels: Fix

#256 NPC 애니메이션 추가 및 애니메이션 버그 수정
  Client/Assets/Animation/Monster/Skeleton/SkeletonAttack.anim
  Client/Assets/Animation/Monster/Skeleton/SkeletonAttack.anim.meta
  Client/Assets/Animation/Monster/Skeleton/SkeletonIdle.anim
  Client/Assets/Animation/Monster/Skeleton/SkeletonIdle.anim.meta
  Client/Assets/Animation/Monster/Skeleton/SkeletonOverrideController.overrideController
  Client/Assets/Animation/Monster/Skeleton/SkeletonWalk.anim
  Client/Assets/Animation/Monster/Skeleton/SkeletonWalk.anim.meta
  Client/Assets/Animation/TestPilot/TestAnimator.controller
  Client/Assets/Attack_NPC_Skeleton.anim
  Client/Assets/Externals/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Attack.png.meta
  Client/Assets/Externals/Skeleton Sprite Pack/Skeleton/Sprite Sheets/Skeleton Idle.png.meta
  Client/Assets/Resources/Prefabs/AITest.prefab
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scripts/CameraMovement.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
  Client/Assets/Scripts/Items/AttackData.cs
  Client/Assets/Skeleton Attack_0.controller
Labels: Fix

#259 UI:UI얃
  Client/Assets/Animation/UIAnimation/UIDie.anim
  Client/Assets/Animation/UIAnimation/UIDie.anim.meta
  Client/Assets/Animation/UIAnimation/UIDie.controller
  Client/Assets/Animation/UIAnimation/UIDie.controller.meta
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/LobbyScene.unity
Labels: UI

#260 ui:컨트롤러제거
  Client/Assets/Resources/Prefabs/UI/_UI.prefab
  Client/Assets/Scripts/Contoller/InventoryController.cs
  Client/Assets/Scripts/Contoller/LoadingScenController.cs
  Client/Assets/Scripts/UI/UIController.cs
Labels: Fix

#261 카메라 버그 수정 및 UIOption 수정
  Client/Assets/Resources/Prefabs/UI/LobbyLegacy/UIOption.prefab
  Client/Assets/Scripts/CameraMovement.cs
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
Labels: Fix

#262 카메라 서순 문제 수정 및 UIOption 완성
  Client/Assets/Resources/Prefabs/UI/UIOption.prefab
  Client/Assets/Resources/Prefabs/UI/UIOption.prefab.meta
  Client/Assets/Scripts/CameraMovement.cs
Labels: Fix, UI

#264 UIOption 완성
  Client/Assets/Resources/Prefabs/UI/UIOption.prefab
  Client/Assets/Scripts/Character/Defines/Enums.cs
  Client/Assets/Scripts/UI/UIBase.cs
  Client/Assets/Scripts/UI/UIOption.cs
Labels: UI

#265 Inventory system bug reslove song
  Client/Assets/Resources/Prefabs/UI/Lobby/UIOption.prefab
  Client/Assets/Resources/Prefabs/UI/Lobby/UIOption.prefab.meta
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/LoadingScene.unity
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Contoller/InventoryController.cs
  Client/Assets/Scripts/Inventory/InventorySO.cs
  Client/Assets/Scripts/Inventory/Model/PlayerInventory.asset
  Client/Assets/Scripts/UI/UIController.cs
Labels: Feature, Fix, UI

#268 GIt 병합 오류 해결중
  Client/Assets/Resources/Prefabs/UI/UIOption.prefab
  Client/Assets/Resources/Prefabs/UI/UIOption.prefab.meta
  Client/Assets/Scripts/Character/Defines/Enums.cs
  Client/Assets/Scripts/UI/Inventory/UIManager.cs
  Client/Assets/Scripts/UI/Store/UIStore.cs
  Client/Assets/Scripts/UI/UIBase.cs
  Client/Assets/Scripts/UI/UIOption.cs
Labels: Fix

#269 NPC AI 구현 완료 #214
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/LoadingScene.unity
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
  Client/Assets/Scripts/Contoller/InventoryController.cs
  Client/Assets/Scripts/Inventory/InventorySO.cs
  Client/Assets/Scripts/Inventory/Model/PlayerInventory.asset
  Client/Assets/Scripts/UI/UIController.cs
Labels: Feature, Refactor

#270 UIManager 경로에 따라서 가져올 수 있도록 수정
  Client/Assets/Scripts/Contoller/InventoryController.cs
  Client/Assets/Scripts/UI/Inventory/UIManager.cs
  Client/Assets/Scripts/UI/Store/UIStore.cs
  Client/Assets/Scripts/UI/UIOption.cs
Labels: Fix

#271 ui컨트롤러 싱글톤 추가
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scripts/UI/UIController.cs
Labels: Feature

#273 AITest 프리펩 수정
  Client/Assets/Resources/Prefabs/AITest.prefab
  Client/Assets/Scenes/AITestScene/AITestScene.unity
Labels: Fix

#274 UI:DiePanel
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scripts/UI/UIController.cs
Labels: UI

#275 NPCAIController 디버그용 로그 제거, 프리펩 수정 #214
  Client/Assets/Resources/Prefabs/AITest.prefab
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
Labels: Fix, Refactor

#279 스토어 엥커작업끝 - UI:앵커작업씬 - Bugfix:로딩씬 버그수정
  Client/Assets/Resources/Prefabs/UI/Lobby/UIDDAll.prefab
  Client/Assets/Resources/Prefabs/UI/Lobby/UILobby.prefab
  Client/Assets/Resources/Prefabs/UI/Lobby/UIReadyToBattle.prefab
  Client/Assets/Resources/Prefabs/UI/Lobby/UIStore.prefab
  Client/Assets/Resources/Prefabs/UI/Lobby/UIstorage.prefab
  Client/Assets/Resources/Prefabs/UI/_UI.prefab
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/LoadingScene.unity
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scripts/Inventory/Item.meta
  Client/Assets/Scripts/Inventory/Item/EdibleItemSo.cs
  Client/Assets/Scripts/Inventory/Item/EdibleItemSo.cs.meta
  Client/Assets/Scripts/Inventory/Item/MoveSpeedSO.cs
  Client/Assets/Scripts/Inventory/Item/MoveSpeedSO.cs.meta
  Client/Assets/Scripts/Inventory/Model/Item.meta
  Client/Assets/Scripts/Inventory/Model/Item/Potion.asset
  Client/Assets/Scripts/Inventory/Model/Item/Potion.asset.meta
  Client/Assets/Scripts/Inventory/Model/ItemModifiers/AddMoveSpeed.asset
  Client/Assets/Scripts/Inventory/Model/ItemModifiers/AddMoveSpeed.asset.meta
  Client/Assets/Scripts/UI/Store/UIStore.cs
  Client/ProjectSettings/EditorBuildSettings.asset
Labels: Feature, Fix, UI

#283 FarmingTestScene 추가, 사용되지 않는 클래스 제거
  Client/Assets/Scenes/FarmingTestScene.unity
  Client/Assets/Scenes/FarmingTestScene.unity.meta
  Client/Assets/Scripts/WorldObject/BattleFieldObjectManager.cs
  Client/Assets/Scripts/WorldObject/BattleFieldObjectManager.cs.meta
  Client/Assets/Scripts/WorldObject/ObjectPool.cs
  Client/Assets/Scripts/WorldObject/ObjectPool.cs.meta
Labels: Refactor

#284 _UI 프리펩 하위 요소로 FarmingBoxUI 추가
  Client/Assets/Resources/Prefabs/UI/_UI.prefab
  Client/Assets/Scenes/FarmingTestScene.unity
Labels: UI

#286 Camera 프리펩에 raycaster 요소 추가
  Client/Assets/Resources/Prefabs/Camera.prefab
  Client/Assets/Scenes/FarmingTestScene.unity
  Client/Assets/Scripts/Contoller/InventoryController.cs
Labels: Refactor

#285 오디오 기본적인 것 완성
  Client/Assets/Animation/Monster/Skeleton/SkeletonAttack.anim
  Client/Assets/Animation/Monster/Skeleton/SkeletonWalk.anim
  Client/Assets/Animation/TestPilot/TestDodge.anim
  Client/Assets/Animation/TestPilot/TestRun.anim
  Client/Assets/Animation/TestPilot/TestWalk.anim
  Client/Assets/Resources/Prefabs/AITest.prefab
  Client/Assets/Resources/Prefabs/PilotPlayer.prefab
  Client/Assets/Resources/Sounds/MainMixer.mixer
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scripts/Character/Attack/RangeAttack.cs
  Client/Assets/Scripts/Character/CharacterAnimationData.cs
  Client/Assets/Scripts/Character/DataContainer.cs
  Client/Assets/Scripts/Character/Defines/Enums.cs
  Client/Assets/Scripts/Character/Defines/Interfaces.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
  Client/Assets/Scripts/Character/Pilot/CharacterDataContainer.cs
  Client/Assets/Scripts/Character/Pilot/FSM/BaseState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterComboAttackState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterDodgeState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CharacterGroudState.cs
  Client/Assets/Scripts/Character/Pilot/FSM/CombineStateMachine.cs
  Client/Assets/Scripts/Character/Pilot/FSM/StateMachine.cs
  Client/Assets/Scripts/Inventory/Test/RangeMagicSO.asset
  Client/Assets/Scripts/Items/AttackData.cs
  Client/Assets/Scripts/Managers/AttackManager.cs
  Client/Assets/Scripts/Managers/SoundManager.cs
  Client/Assets/Scripts/UI/UIOption.cs
  Client/ProjectSettings/TagManager.asset
Labels: Feature, Fix

#288 믹서에 대한 내용 사운드매니저에 적용
  Client/Assets/Resources/Prefabs/Manager/SoundManager.prefab
  Client/Assets/Resources/Sounds/MainMixer.mixer
Labels: Fix

#289 FarmingBox UI 에서 아이템이 사용되지 않는 오류 수정
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
Labels: Fix, Refactor

#290 Init stat
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scenes/LoginScene.unity
  Client/Assets/Scripts/Contoller/LoginSceneController.cs
Labels: Bug

#291 Ambient 소리 Loop및 설정 적용토록 수정.
  Client/Assets/Scripts/Managers/SoundManager.cs
Labels: Fix

#292 옵션창 소리 적용
  Client/Assets/Resources/Prefabs/UI/UIOption.prefab
  Client/Assets/Resources/Sounds/MainMixer.mixer
  Client/Assets/Scripts/Managers/SoundManager.cs
  Client/Assets/Scripts/UI/UIOption.cs
Labels: Feature, Fix

#293 커스텀 싱글톤 무조건 DontDestroyOnLoad해두고 클론 프리펩 수정
  Client/Assets/Resources/Prefabs/ClonePlayer.prefab
  Client/Assets/Scripts/Utils/CustomSingleton.cs
Labels: Fix

#294 클론 애니메이션 연동 오류 수정
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Resources/Prefabs/Player.prefab.meta
  Client/Assets/Scripts/Character/Clone/AnimationControllerFSM/CloneStateMachine.cs
  Client/Assets/Scripts/Character/Clone/CloneDataContainer.cs
Labels: Fix

#296 플래이어의 생성 시점에 맞추어 카메라 이동
  Client/Assets/Scripts/CameraMovement.cs
Labels: Fix

#297 FarmingBox 여닫을 때 효과음, 전투 시 배경음 전환 구현
  Client/Assets/Scenes/FarmingTestScene.unity
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
  Client/Assets/Scripts/Contoller/InventoryController_FB.cs
  Client/Assets/Scripts/WorldObject/BattleFieldObject.cs
  Client/Assets/Scripts/WorldObject/FarmingBox.cs
Labels: Feature

#298 ui사운드추가
  Client/Assets/Scenes/LobbyScene.unity
  Client/Assets/Scripts/Contoller/InventoryController.cs
  Client/Assets/Scripts/Inventory/PickUpSystem/PickUpSystem.cs
  Client/Assets/Scripts/UI/Inventory/UIInventoryPage.cs
  Client/Assets/Scripts/UI/Store/UIStorePopup.cs
Labels: UI

#299 ObjectManager 수정
  Client/Assets/Scripts/Managers/ObjectManager.cs
Labels: Fix, Bug

#300 싱글톤 버그 및 사운드매니저 수정
  Client/Assets/Scripts/Managers/SoundManager.cs
  Client/Assets/Scripts/Utils/CustomSingleton.cs
Labels: Fix

#301 UI Option 수정
  Client/Assets/Resources/Prefabs/UI/UIOption.prefab
Labels: Fix

#302 Bug eater
  Client/Assets/Scenes/BattleGroundScene.unity
Labels: Fix

#305 FarmingBox 파트 병합
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/FarmingTestScene.unity
  Client/Assets/Scripts/Character/NPC/NPCAIController.cs
  Client/Assets/Scripts/Character/NPC/NPCDataContainer.cs
Labels: Merge

#306 라이팅맵 적용
  Client/Assets/Externals/greyRoadStudio/LowPolyTreePack/Materials/Mat_Ground.mat
  Client/Assets/Scenes/BattleGroundScene.unity
  Client/Assets/Scenes/BattleGroundScene/LightingData.asset
Labels: Fix

#307 UI 플래이어 정보 복구하기
  Client/Assets/Scenes/BattleGroundScene.unity
Labels: Fix
