Repository Team-Omoshiroi/Omoshiroi, pull requests merged in 2023-10, with the labels that each got.

#9 Client/MultiplayTestSetting
  Client/Assets/NuGet.config.meta
  Client/Assets/Scripts/Editor.meta
  Client/Assets/Scripts/Editor/MultiplayerBuildAndRun.cs
  Client/Assets/Scripts/Editor/MultiplayerBuildAndRun.cs.meta
  Client/Assets/packages.config.meta
Labels: Feature

#10 Client/NetworkManager
  Client/Assets/Scripts/Managers.meta
  Client/Assets/Scripts/Managers/NetworkManager.cs
  Client/Assets/Scripts/Managers/NetworkManager.cs.meta
  Client/Assets/Scripts/Packet/ServerSession.cs
  Client/Assets/Scripts/Utils.meta
  Client/Assets/Scripts/Utils/CustomSingleton.cs
  Client/Assets/Scripts/Utils/CustomSingleton.cs.meta
Labels: Feature

#18 UI Base와 UIManager를 가져옴
  Client/Assets/Scripts/UI/UIBase.cs
  Client/Assets/Scripts/UI/UIManager.cs
  Client/Assets/Scripts/UI/UIManager.cs.meta
Labels: Feature

#19 UI 숨김, 닫음 방법에 대한 통일
  Client/Assets/Scripts/UI/UIBase.cs
  Client/Assets/Scripts/UI/UIManager.cs
Labels: Refactor

#22 ItemSO 임시 구현 #14
  Client/Assets/Data/Scripts/Items/BaseConsumable.cs
  Client/Assets/Data/Scripts/Items/BaseItem.cs
  Client/Assets/Data/Scripts/Items/BaseRune.cs
  Client/Assets/Data/Scripts/Items/BaseSkin.cs
Labels: Feature

#23 ItemSO 기본 틀 구현 #14
  Client/Assets/Data/Scripts/Items/BaseConsumable.cs
  Client/Assets/Data/Scripts/Items/BaseMagic.cs
  Client/Assets/Data/Scripts/Items/BaseMagic.cs.meta
  Client/Assets/Data/Scripts/Items/BaseResource.cs
  Client/Assets/Data/Scripts/Items/BaseResource.cs.meta
  Client/Assets/Data/Scripts/Items/BaseWeapon.cs
  Client/Assets/Data/Scripts/Items/BaseWeapon.cs.meta
Labels: Feature

#24 Main UI hwan
  Client/Assets/Scripts/UI/UIBase.cs
  Client/Assets/Scripts/UI/UIManager.cs
  Client/Assets/Scripts/Utils/PlainSingleton.cs
  Client/Assets/Scripts/Utils/PlainSingleton.cs.meta
Labels: Feature, Refactor, UI

#25 Input 시리즈 기본 틀 구현 #13
  Client/Assets/Scripts/Character.meta
  Client/Assets/Scripts/Character/Input.meta
  Client/Assets/Scripts/Character/Input/BaseInput.cs
  Client/Assets/Scripts/Character/Input/BaseInput.cs.meta
  Client/Assets/Scripts/Character/Input/EnemyInput.cs
  Client/Assets/Scripts/Character/Input/EnemyInput.cs.meta
  Client/Assets/Scripts/Character/Input/NPCInput.cs
  Client/Assets/Scripts/Character/Input/NPCInput.cs.meta
  Client/Assets/Scripts/Character/Input/PlayerInput.cs
  Client/Assets/Scripts/Character/Input/PlayerInput.cs.meta
Labels: Feature

#26 Battle character hwan
  Client/Assets/InputSystems.meta
  Client/Assets/InputSystems/ThirdPersonController.cs
  Client/Assets/InputSystems/ThirdPersonController.cs.meta
  Client/Assets/InputSystems/ThirdPersonController.inputactions
  Client/Assets/InputSystems/ThirdPersonController.inputactions.meta
  Client/Assets/Scripts/Character/AnimationController.meta
  Client/Assets/Scripts/Character/AnimationController/PlayerAnimationController.cs
  Client/Assets/Scripts/Character/AnimationController/PlayerAnimationController.cs.meta
  Client/Assets/Scripts/Character/CharacterDataContainer.cs
  Client/Assets/Scripts/Character/CharacterDataContainer.cs.meta
  Client/Assets/Scripts/Character/CharacterMovement.cs
  Client/Assets/Scripts/Character/CharacterMovement.cs.meta
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Character/CharacterStats.cs.meta
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Character/HealthSystem.cs.meta
Labels: Feature

#27 BaseMagic, BaseWeapon 멤버변수 추가 #14
  Client/Assets/Data/Scripts.meta
  Client/Assets/Data/Scripts/Items/BaseMagic.cs
  Client/Assets/Data/Scripts/Items/BaseWeapon.cs
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Items.meta
  Client/Assets/Scripts/Items/BaseConsumable.cs
  Client/Assets/Scripts/Items/BaseConsumable.cs.meta
  Client/Assets/Scripts/Items/BaseItem.cs
  Client/Assets/Scripts/Items/BaseItem.cs.meta
  Client/Assets/Scripts/Items/BaseMagic.cs
  Client/Assets/Scripts/Items/BaseMagic.cs.meta
  Client/Assets/Scripts/Items/BaseResource.cs
  Client/Assets/Scripts/Items/BaseResource.cs.meta
  Client/Assets/Scripts/Items/BaseRune.cs
  Client/Assets/Scripts/Items/BaseRune.cs.meta
  Client/Assets/Scripts/Items/BaseSkin.cs
  Client/Assets/Scripts/Items/BaseSkin.cs.meta
  Client/Assets/Scripts/Items/BaseWeapon.cs
  Client/Assets/Scripts/Items/BaseWeapon.cs.meta
Labels: Feature

#30 CharacterDataContainer, CharacterStats, EquipSystem 추가 #28
  Client/Assets/Scripts/Character/CharacterDataContainer.cs
  Client/Assets/Scripts/Character/EquipSystem.cs
  Client/Assets/Scripts/Character/EquipSystem.cs.meta
  Client/Assets/Scripts/Character/HealthSystem.cs
Labels: Feature

#31 Battle character hwan
  Client/Assets/InputSystems/ThirdPersonController.cs
  Client/Assets/InputSystems/ThirdPersonController.inputactions
  Client/Assets/Resources.meta
  Client/Assets/Resources/Prefabs.meta
  Client/Assets/Resources/Prefabs/Player.prefab
  Client/Assets/Resources/Prefabs/Player.prefab.meta
  Client/Assets/Scenes/PlayerTestScene.unity
  Client/Assets/Scenes/PlayerTestScene.unity.meta
  Client/Assets/Scripts/Character/CharacterMovement.cs
  Client/Assets/Scripts/Character/Input/BaseInput.cs
  Client/Assets/Scripts/Character/Input/PlayerInput.cs
  Client/ProjectSettings/SceneTemplateSettings.json
Labels: Feature, Refactor

#32 장비 장착/탈착 기능 재구성 #28
  Client/Assets/Scripts/Character/CharacterDataContainer.cs
  Client/Assets/Scripts/Character/CharacterStats.cs
  Client/Assets/Scripts/Character/EquipSystem.cs
  Client/Assets/Scripts/Character/HealthSystem.cs
  Client/Assets/Scripts/Defines/Interfaces.cs
  Client/Assets/Scripts/Items/BaseMagic.cs
  Client/Assets/Scripts/Items/BaseRune.cs
  Client/Assets/Scripts/Items/BaseSkin.cs
  Client/Assets/Scripts/Items/BaseWeapon.cs
Labels: Refactor

#33 Stackable 객체에 멤버변수 maxStack 추가 #14
  Client/Assets/Scripts/Items/BaseConsumable.cs
  Client/Assets/Scripts/Items/BaseResource.cs
Labels: Feature
